"""empty message

Revision ID: 12072b375729
Revises: 44d1e31d5a30
Create Date: 2024-05-05 23:42:30.185446

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12072b375729'
down_revision = '44d1e31d5a30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_name', sa.String(length=35), nullable=False))
        batch_op.create_unique_constraint(None, ['user_name'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('user_name')

    # ### end Alembic commands ###
